plugins {
	id "net.minecraftforge.gradle" version "[6.0,6.2)"
	id "maven-publish"
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

sourceSets {
	main {
		java.setSrcDirs(["src/legacyForge/java"])
		resources.setSrcDirs(["src/legacyForge/resources"])
	}
	test {
		java.setSrcDirs(["src/legacyForgeTest/java"])
	}
}

minecraft {
	mappings channel: "official", version: project.minecraft_version
	runs {
		client {
			workingDirectory project.file("run")
			property "forge.logging.console.level", "info"
			mods { ai_companion { source sourceSets.main } }
		}
		server {
			workingDirectory project.file("run-server")
			property "forge.logging.console.level", "info"
			mods { ai_companion { source sourceSets.main } }
		}
	}
}

dependencies {
	minecraft "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
}

processResources {
	inputs.property "version", project.version
	filesMatching("META-INF/mods.toml") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	options.release = 17
	options.encoding = "UTF-8"
}

jar {
	manifest {
		attributes([
			"Specification-Title": "ai_companion",
			"Specification-Vendor": "WindowsdePC",
			"Specification-Version": project.version,
			"Implementation-Title": project.name,
			"Implementation-Version": project.version,
			"Implementation-Vendor": "WindowsdePC"
		])
	}
	from("LICENSE") { rename { "${it}_${project.name}" } }
	finalizedBy "reobfJar"
}
